# Dict data into DataFrame

If data stored in dictionary, list or tuple then we can behaves them as it's method and attribute.

In [ ]:
import pandas as pd
import numpy as np

# Columns are specify in sequence order

In [ ]:
data = {'HeadPhone':[500,1000,1500,2000,4000,5000],
        'SmartWatch':[550,150,1000,500,600,8000],
        'EarPhone':[400,100,500,600,2000,1000]}

size = list(data.values())[0]
data['S.N.'] = list(range(1, len(size)+1))
df = pd.DataFrame(data, columns=['S.N.','EarPhone','HeadPhone','SmartWatch'], index=(range(1, len(size)+1)))
df

   S.N.  EarPhone  HeadPhone  SmartWatch
1     1       400        500         550
2     2       100       1000         150
3     3       500       1500        1000
4     4       600       2000         500
5     5      2000       4000         600
6     6      1000       5000        8000

# Columns in DataFrame can be retrived as Series either by dict notation or by attribute

In [ ]:
# By dict notation
df['EarPhone']

# By attribute
df.HeadPhone

1     500
2    1000
3    1500
4    2000
5    4000
6    5000
Name: HeadPhone, dtype: int64

# Columns can be modified by assingment

In [ ]:
# df['Eyeglass'] = np.arange(100,106)
# df

df['Boost Mp3'] = [450,5220,235,909,900,300]
# Delete column data
# del df['Boost Mp3'] 
df
# Slicing of dataframe
# df[:2]

   S.N.  EarPhone  HeadPhone  SmartWatch  Boost Mp3
1     1       400        500         550        450
2     2       100       1000         150       5220
3     3       500       1500        1000        235
4     4       600       2000         500        909
5     5      2000       4000         600        900
6     6      1000       5000        8000        300

# Nested format data stored

All nested/inner keys are becomes indices and all nested values are becomes a column.
Each first keys are labels in column

In [ ]:
data = {'ChatGPT':{'Version 1': 2.1, 'Version 2':2.5, 'Version 3':3.1, 'Version 4':3.6, 'Version 5':4.0, 'Version 6':5.0},
        'Claud Sonnet':{'Version 1':2.5, 'Version 2':3.1, 'Version 3':3.4, 'Version 4':3.6, 'Version 5':3.9, 'Version 6':4.5}}

df = pd.DataFrame(data)
df

# Also can transpose the data
# df.T


# Values attribute returns 2D ndarray
# df.values

# Keys attribute returns NDframe
# df.keys

           ChatGPT  Claud Sonnet
Version 1      2.1           2.5
Version 2      2.5           3.1
Version 3      3.1           3.4
Version 4      3.6           3.6
Version 5      4.0           3.9
Version 6      5.0           4.5

# List of dicts

Each items are specify in rows
Each keys label in column and values are becomes a column.

In [ ]:
data = [{'Python':'3.14.0', 'C++':'4.8.9', 'Java':'4.05'}, {'Python':'3.14.1', 'C++':'4.9.9', 'Java':'4.8.5'}]
pd.DataFrame(data)

   Python    C++   Java
0  3.14.0  4.8.9   4.05
1  3.14.1  4.9.9  4.8.5

# Series data into DataFrame

In [ ]:
data = ['Computer','Laptop', 'Smart Watch']
pd.DataFrame(data, columns=['Tech'], index=[1,2,3])

          Tech
1     Computer
2       Laptop
3  Smart Watch